AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  AWS SAM Template for Multi-Lambda Microservices

Parameters:
  ExistingBucketName:
    Type: String
    Description: Name of the existing S3 bucket that will trigger the Orchestrator Lambda
    Default: "etllambdatest"

Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Resources:

  # Orchestrator Lambda (Triggered by S3 PutObject)
  OrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/orchestrator/
      Handler: app.orch_lambda
      Runtime: python3.13
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:  # Allows this Lambda to read from S3
            BucketName: !Ref ExistingBucketName
        - Statement:  # Add this to allow invoking other Lambdas
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt SQLDocketIngestFunction.Arn
      Events:
        S3PutEvent:
          Type: S3
          Properties:
            Bucket: !Ref ExistingBucketName
            Events: s3:ObjectCreated:*

  # SQL Docket Ingest Lambda (Triggered by Orchestrator)
  SQLDocketIngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/sql_docket_ingest/
      Handler: app.handler
      Runtime: python3.13
      VpcConfig:
        SecurityGroupIds:
          - sg-03e2bf8d3930f3c42
        SubnetIds:
          - subnet-0548c79ad1faa1117
          - subnet-0e157bfea98242a74
      Layers:
        - arn:aws:lambda:us-east-1:936771282063:layer:psycopg-import:1
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonRDSDataFullAccess  # Allows writing to Aurora
        - Version: '2012-10-17'  # Add Secrets Manager permissions
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: "arn:aws:secretsmanager:us-east-1:936771282063:secret:mirrulationsdb/postgres/master-uA4mKl"  
      Environment:
        Variables:
          # Remove or replace these with your DB_SECRET_NAME environment variable
          # AURORA_CLUSTER_ARN: "arn:aws:rds:us-east-1:123456789012:cluster:my-cluster"
          # AURORA_SECRET_ARN: "arn:aws:secretsmanager:us-east-1:123456789012:secret:my-secret"
          # DB_SECRET_NAME: "your-database-secret-name"  # Name of your secret in Secrets Manager

Outputs:

  OrchestratorFunctionArn:
    Description: "Orchestrator Lambda Function ARN"
    Value: !GetAtt OrchestratorFunction.Arn

  SQLDocketIngestFunctionArn:
      Description: "SQL Docket Ingest Lambda Function ARN"
      Value: !GetAtt SQLDocketIngestFunction.Arn